# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'RnKeyboard' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RnKeyboard

end
